<h3><?php use const StudentUtility\LOCALE_DOMAIN;

    esc_html_e('Student Personal Information', LOCALE_DOMAIN); ?></h3>

<table class="form-table">
    <tr>
        <th><label for="numberOfStudentCard"><?php esc_html_e('Number of student card', LOCALE_DOMAIN); ?></label></th>
        <td><?php echo $data['numberOfStudentCard'] ?></td>
    </tr>
    <tr>
        <th><label for="middleNameOfStudent"><?php esc_html_e('Middle name of student', LOCALE_DOMAIN); ?></label></th>
        <td><?php echo $data['middleNameOfStudent'] ?></td>
    </tr>
</table>